(* =====================================================================
   bfs_sat.m
   Separating-axis replacement for the RegionMeasure/RegionIntersection
   validity test in face_rotation_net_all4D_v2.m.

   Why: checkRootV2 builds nCP ConvexHullMesh objects per root and runs
   RegionIntersection on the candidate pairs.  At 2640 cells that is
   ~20 s per root, so all roots for one H4 member would take ~15 h.

   What changed, in the order the profiler forced them (x5x3x3x, 2640
   cells, per root: 19.8 s with RegionMeasure -> 10.7 -> 8.5 -> 1.5 s)
     - cell overlap: SAT (face normals first, edge x edge only if those
       fail), ported from unfold3DExport.m.  No meshes, no region
       algebra.  This ended up costing 0.04 s, i.e. nothing.
     - per-cell SAT combinatorics (which vertex triples give face
       normals, which pairs give edge directions) precomputed ONCE per
       polytope instead of per root.
     - faceUp and the unfolding transforms vectorized as matrix products;
       the BFS visited set turned from a list scanned with MemberQ into
       an Association (that scan was O(C^2)).
     - candidate pairs: the dense C x C bounding-box comparison then
       dominated at 6.9 s, so it was replaced by a radius query on cell
       centroids (see satBBoxPairs).

   Semantics: satOverlapQ with eps > 0 treats contact along a shared face
   as separated, matching the "boundary contact is not an overlap" rule
   of the volume test.  The two tests are NOT identical by construction
   (a sliver thinner than eps but of volume > epsVol would differ), which
   is why validate_sat.m re-runs all 1893 roots of the 30 A4/B4/F4
   polytopes and demands the previous per-root overlap counts back.

   Provides: satPrepCells[], checkRootSAT[r]
   Assumes the globals versP/facesP/cellsP/nCP/versCenteredP/adjSetP/
   adjListP are already set, as in the other runners.
   ===================================================================== *)

ClearAll[satEps, satCellIdx, satFaceTri, satEdgePair,
         satPrepCells, satNormalsEdges, satOverlapQ, satBBoxPairs,
         satFaceUp, satBfsUnfold, checkRootSAT];

satEps = 10^-6;

(* ---------------------------------------------------------------- *)
(* Per-polytope precomputation                                       *)
(* ---------------------------------------------------------------- *)

satPrepCells[] := Module[{},
  satCellIdx  = Table[Union @@ facesP[[cellsP[[i]]]], {i, nCP}];
  satFaceTri  = Table[
    Module[{loc = AssociationThread[satCellIdx[[i]] -> Range[Length[satCellIdx[[i]]]]]},
     Lookup[loc, #] & /@ (Take[facesP[[#]], 3] & /@ cellsP[[i]])],
    {i, nCP}];
  satEdgePair = Table[
    Module[{loc = AssociationThread[satCellIdx[[i]] -> Range[Length[satCellIdx[[i]]]]]},
     Lookup[loc, #] & /@ DeleteDuplicates[
       Sort /@ Flatten[Partition[facesP[[#]], 2, 1, 1] & /@ cellsP[[i]], 1]]],
    {i, nCP}];
  ];

(* face normals and edge directions of one placed cell *)
satNormalsEdges[pts_, tri_, epr_] := Module[{nm, ed},
  nm = Cross[pts[[#[[2]]]] - pts[[#[[1]]]],
             pts[[#[[3]]]] - pts[[#[[1]]]]] & /@ tri;
  nm = Normalize /@ Select[nm, Norm[#] > 10^-10 &];
  ed = (pts[[#[[2]]]] - pts[[#[[1]]]]) & /@ epr;
  ed = Normalize /@ Select[ed, Norm[#] > 10^-10 &];
  {DeleteDuplicatesBy[nm, Round[#/10^-9] &],
   DeleteDuplicatesBy[ed, Round[Sign[First[SortBy[#, Abs[#] > 10^-9 &]]] #/10^-9] &]}];

(* SAT: True = the two convex cells genuinely overlap *)
satOverlapQ[ptsA_, nA_, eA_, ptsB_, nB_, eB_] := Catch[
  Do[Module[{pa = ptsA . ax, pb = ptsB . ax},
     If[Max[pa] <= Min[pb] + satEps || Max[pb] <= Min[pa] + satEps,
      Throw[False]]],
   {ax, Join[nA, nB]}];
  Do[Module[{c = Cross[ea, eb], cn, pa, pb},
     cn = Norm[c];
     If[cn > 10^-10,
      c = c/cn; pa = ptsA . c; pb = ptsB . c;
      If[Max[pa] <= Min[pb] + satEps || Max[pb] <= Min[pa] + satEps,
       Throw[False]]]],
   {ea, eA}, {eb, eB}];
  True];

(* Candidate pairs.  The dense C x C bounding-box comparison was the
   dominant cost at C = 2640 (18 array operations on 7M-entry matrices),
   so the pair list is instead generated by a radius query on the cell
   centroids: two cells can only meet if their centroids are within
   R_i + R_j, bounded by twice the largest circumradius.  Everything
   after the query is vectorized over the packed pair list. *)
satBBoxPairs[cent_, bMin_, bMax_, radius_] := Module[
  {nbrs, pairs, i1, j1, ok},
  nbrs = Nearest[cent -> Automatic][cent, {All, radius}];
  pairs = Join @@ MapIndexed[
    Function[{ns, k}, Module[{i = First[k], up = Select[ns, # > First[k] &]},
      Transpose[{ConstantArray[i, Length[up]], up}]]], nbrs];
  If[pairs === {} || Length[pairs] === 0, Return[{}]];
  (* pairs already satisfy j > i, so only adjacency has to be removed *)
  pairs = Pick[pairs, Lookup[adjSetP, pairs, False], False];
  If[Length[pairs] === 0, Return[{}]];
  i1 = pairs[[All, 1]]; j1 = pairs[[All, 2]];
  ok = Times @@ Table[
     UnitStep[bMax[[j1, k]] - bMin[[i1, k]]] *
     UnitStep[bMax[[i1, k]] - bMin[[j1, k]]], {k, 3}];
  Pick[pairs, ok, 1]];

(* vectorized replacements for the two hot spots inherited from
   face_rotation_net_all4D_v2.m.  Same arithmetic, same traversal order. *)
satFaceUp[r_, locV_] := Module[{cc, wHat = {0., 0., 0., 1.}, angle, R},
  cc = Mean[locV[[satCellIdx[[r]]]]];
  Which[
   Abs[(cc/Norm[cc]) . wHat - 1] < 0.0001, locV,
   Abs[(cc/Norm[cc]) . wHat + 1] < 0.0001, -locV,
   True,
   angle = ArcCos[Clip[cc . wHat/Norm[cc], {-1., 1.}]];
   R = RotationMatrix[angle, {cc/Norm[cc], wHat}];
   locV . Transpose[R]]];

(* same BFS tree as bfsUnfoldP, but the visited set is an Association
   instead of a growing list scanned with MemberQ *)
satBfsUnfold[root_] := Module[{q = {root}, head = 1, vis, tfs, par},
  vis = <|root -> True|>;
  tfs = <|root -> idAff4|>;
  While[head <= Length[q],
   par = q[[head]]; head++;
   Do[If[! KeyExistsQ[vis, nb],
      vis[nb] = True; AppendTo[q, nb];
      tfs[nb] = unfoldTFP[par, nb, tfs[par]]],
    {nb, adjListP[[par]]}]];
  tfs];

(* ---------------------------------------------------------------- *)
(* One root                                                          *)
(* ---------------------------------------------------------------- *)

checkRootSAT[r_] := Module[
  {tfsR, unf3D, bMin, bMax, cent, radius, cand, ne, hits},
  versP = satFaceUp[r, versCenteredP];
  tfsR  = satBfsUnfold[r];
  unf3D = Table[
    Module[{tf = tfsR[i]},
     Take[#, 3] & /@ (versP[[satCellIdx[[i]]]] . Transpose[tf[[1]]] +
                      Threaded[tf[[2]]])], {i, nCP}];

  bMin = (Min /@ Transpose[#]) & /@ unf3D;
  bMax = (Max /@ Transpose[#]) & /@ unf3D;
  cent = Mean /@ unf3D;
  (* radius = 2 * largest circumradius bounds R_i + R_j for every pair *)
  radius = 2 * Max[MapThread[
     Function[{pts, c}, Max[Norm[# - c] & /@ pts]], {unf3D, cent}]];
  cand = satBBoxPairs[cent, bMin, bMax, radius];
  If[Length[cand] === 0, Return[{r, 0, 0, True}]];

  (* only the cells that survive the prefilter need axes *)
  ne = Association@Table[
     c -> satNormalsEdges[unf3D[[c]], satFaceTri[[c]], satEdgePair[[c]]],
     {c, Union @@ cand}];

  hits = Select[cand, Function[p,
     satOverlapQ[unf3D[[p[[1]]]], ne[p[[1]]][[1]], ne[p[[1]]][[2]],
                 unf3D[[p[[2]]]], ne[p[[2]]][[1]], ne[p[[2]]][[2]]]]];

  {r, Length[cand], Length[hits], Length[hits] === 0}];
