(* =====================================================================
   uniform4D_wythoff.m
   Wythoff construction of convex uniform 4-polytopes.
   Scope: the A4, B4 and F4 families (Wythoffian members only).

   w4Build[...]["data"] is a 6-element list following the _4DData/f*.m
   convention:
     [[1]] verts       : vertex coordinates in R^4
     [[2]] edges       : vertex-index pairs, each edge once
     [[3]] vertAdj     : for each vertex, the adjacent vertices
     [[4]] facesByVert : 2-faces as vertex-index lists, CYCLIC order
     [[5]] faceAdj     : for each face, the faces sharing an edge
     [[6]] cellsByFace : cells as face-index lists
   face_rotation_net_all4D_v2.m consumes [[1]], [[4]] and [[6]].
   Cells as vertex-index lists are returned separately under "cellsV".

   Note on the existing files: f8.m lists each of the 32 tesseract edges
   in both directions ([[2]] has 64 entries), while f5/f16/f24 list each
   edge once.  Nothing reads [[2]], so this is harmless; we emit the
   undirected convention.

   Faces are stored in cyclic order on purpose: unfoldTFP builds the
   rotation plane from the first two vertices of the shared face, which
   degenerates if they happen to be antipodal (e.g. a square listed in
   sorted index order).

   Method
     - Coxeter marks -> Gram matrix -> unit mirror normals (Cholesky)
     - group W = closure of the four reflections
     - seed point p solves  n_i . p = b_i  (b_i = 1 ringed, 0 unringed).
       The edge generated by mirror i has length 2 b_i, so equal b_i
       forces equal edge lengths, i.e. a uniform polytope.
     - vertices = orbit of p under W
     - cells: for each i the maximal parabolic W_J, J = {1,2,3,4}\{i},
       stabilizes a facet.  Orbit that facet's hyperplane under W; the
       vertices lying on each hyperplane form a cell.
     - ridges (2-faces) = pairwise intersections of cells, since every
       ridge of a convex 4-polytope lies in exactly two facets.

   Self-checks (independent of any table of published counts)
     - |W| against the known order of the Coxeter group
     - V  against the index |W| / |W_unringed|, since the stabilizer of
       the seed point is exactly the parabolic on the unringed nodes
     - C  against sum_i |W| / |W_{J_i}| over the facet-bearing nodes
     - Euler relation V - E + F - C = 0
     - every facet hyperplane actually supports the polytope

   NOT covered: the alternated/snub forms (snub 24-cell) and the
   non-Wythoffian grand antiprism.  Those need separate constructions.

   Scaling note: the ridge step is O(C^2) in the number of cells, which
   is fine up to F4 (C <= 240) but will need replacing for H4, where the
   omnitruncated 120-cell has 2640 cells.  The fix is to build ridges
   from the rank-2 parabolics W_{J}, J = {1..4}\{i,j}, and to recover
   the two incident cells with a single vectorized centroid-times-normal
   matrix product.

   Usage
     Get["<baseDir>/uniform4D_wythoff.m"]     (* runs the full report *)
     data = w4Build[w4MarksA, {1,1,0,0}];     (* truncated 5-cell *)
   ===================================================================== *)

ClearAll[w4Prec, w4Grid, w4Tol, w4Key, w4Gram, w4Normals, w4Refl,
         w4Group, w4Seed, w4Orbit, w4Build, w4Report, w4Symbol,
         w4MarksA, w4MarksB, w4MarksF, w4Patterns, w4RunFamily,
         w4Export, w4Compare4DData];

w4Prec = 30;        (* working precision                        *)
w4Grid = 10^-10;    (* hashing grid; keys are exact integers    *)
w4Tol  = 10^-7;     (* geometric tolerance                      *)

(* Integer hash key.  Note Round[x, dx] would return a precision-carrying
   real, which is unusable as an Association key; Round[x/dx] is exact. *)
w4Key[x_] := Round[x/w4Grid];

(* ---------------------------------------------------------------- *)
(* Coxeter data                                                      *)
(* ---------------------------------------------------------------- *)

(* marks[[i,j]] = m_ij, the Coxeter mark (2 = unconnected nodes) *)
w4Marks[chain_] :=
  Table[Which[i === j, 1,
              j === i + 1, chain[[i]],
              i === j + 1, chain[[j]],
              True, 2],
        {i, 4}, {j, 4}];

w4MarksA = w4Marks[{3, 3, 3}];   (* A4, order   120, 5-cell family    *)
w4MarksB = w4Marks[{4, 3, 3}];   (* B4, order   384, tesseract family *)
w4MarksF = w4Marks[{3, 4, 3}];   (* F4, order  1152, 24-cell family   *)
w4MarksH = w4Marks[{5, 3, 3}];   (* H4, order 14400, 120-cell family  *)

(* H4 costs a few minutes; scripts that only need A4/B4/F4 can Get this
   file without paying for it.  Set w4IncludeH4 = True before Get to
   include it. *)
If[! ValueQ[w4IncludeH4], w4IncludeH4 = False];

w4Gram[marks_] :=
  Table[If[i === j, 1, -Cos[Pi/marks[[i, j]]]], {i, 4}, {j, 4}];

(* rows of the result are the unit normals n_1..n_4 *)
w4Normals[marks_] :=
  N[Transpose[CholeskyDecomposition[w4Gram[marks]]], w4Prec];

w4Refl[n_] := IdentityMatrix[4] - 2 Outer[Times, n, n];

(* Coxeter's x/o symbol, e.g. {1,1,0,0} on A4 -> "x3x3o3o" *)
w4Symbol[marks_, rings_] :=
  StringJoin @ Riffle[
    If[# =!= 0, "x", "o"] & /@ rings,
    ToString /@ Table[marks[[i, i + 1]], {i, 3}]];

(* ---------------------------------------------------------------- *)
(* Group closure                                                     *)
(* ---------------------------------------------------------------- *)

w4Group[gens_] := Module[{id, seen, frontier, sown},
  id = N[IdentityMatrix[4], w4Prec];
  seen = <|w4Key[id] -> id|>;
  frontier = {id};
  While[frontier =!= {},
   sown = Reap[
      Do[Module[{m = g . h, k},
        k = w4Key[m];
        If[! KeyExistsQ[seen, k], seen[k] = m; Sow[m]]],
       {h, frontier}, {g, gens}]][[2]];
   frontier = If[sown === {}, {}, First[sown]]];
  Values[seen]];

(* seed point: n_i . p = rings[[i]] *)
w4Seed[normals_, rings_] := LinearSolve[normals, N[rings, w4Prec]];

w4Orbit[group_, p_] := Module[{seen = <||>},
  Do[With[{q = g . p}, seen[w4Key[q]] = q], {g, group}];
  Values[seen]];

(* ---------------------------------------------------------------- *)
(* Main construction                                                 *)
(* ---------------------------------------------------------------- *)

w4Build[marks_, rings_] := Module[
  {nrm, refl, grp, nW, p, verts, nv, planes, subOrders, J, sub, cpts,
   diffs, m, c, dots, cellsV, nc, vkey, vAt, rpts, faceSet, faces,
   vertCells, faceCells, badRidges, cyc, edges, vertAdj,
   edgeMap, cellsF, faceAdj, badPlanes, stabOrder, predV, predC},

  nrm  = w4Normals[marks];
  refl = w4Refl /@ nrm;
  grp  = w4Group[refl];
  nW   = Length[grp];
  p    = w4Seed[nrm, rings];

  (* --- vertices --- *)
  verts = w4Orbit[grp, p];
  nv    = Length[verts];

  (* predicted V: the stabilizer of p is the parabolic on unringed nodes *)
  stabOrder = Length@w4Group[refl[[Flatten@Position[rings, 0]]]];
  predV = nW/stabOrder;

  (* --- facet hyperplanes {normal, offset} --- *)
  subOrders = {};
  planes = Reap[
    Do[
     J    = Delete[Range[4], i];
     sub  = w4Group[refl[[J]]];
     cpts = w4Orbit[sub, p];
     diffs = (# - First[cpts]) & /@ cpts;
     If[MatrixRank[diffs, Tolerance -> w4Tol] === 3,
      AppendTo[subOrders, Length[sub]];
      m = Normalize@First@NullSpace[diffs, Tolerance -> w4Tol];
      c = m . First[cpts];
      If[c < 0, m = -m; c = -c];
      (* origin is interior, so no facet hyperplane passes through it *)
      If[c > w4Tol, Do[Sow[{g . m, c}], {g, grp}]]],
     {i, 4}]][[2]];
  planes = If[planes === {}, {},
              DeleteDuplicatesBy[First[planes], w4Key[First[#]] &]];
  predC = Total[nW/subOrders];

  (* --- cells: vertices lying on each facet hyperplane ---
     Vectorized: one matrix-vector product per plane.  The old
     Select[Range[nv], ... verts[[#]] ...] form did O(C*V) interpreted
     dot products and did not scale past F4. *)
  dots   = Table[verts . pl[[1]], {pl, planes}];
  cellsV = MapThread[
    Pick[Range[nv], Thread[Abs[#1 - #2] < w4Tol]] &,
    {dots, planes[[All, 2]]}];
  nc = Length[cellsV];

  (* sanity: every hyperplane must support the polytope *)
  badPlanes = Count[
    MapThread[Max[#1] - #2 &, {dots, planes[[All, 2]]}],
    x_ /; x > w4Tol];

  (* --- ridges: orbits of the rank-2 parabolics ---
     The d-faces of a Wythoffian polytope are the orbits of the rank-d
     parabolic subgroups.  Orbiting the prototype's VERTEX SET under W
     costs O(|W| * polygon size) and replaces the old O(C^2) scan over
     pairs of cells, which is what blocked H4. *)
  vkey = AssociationThread[w4Key /@ verts -> Range[nv]];
  vAt  = Function[q, Lookup[vkey, Key[w4Key[q]], 0]];

  faceSet = <||>;
  Do[
   sub  = w4Group[refl[[{i, j}]]];
   rpts = w4Orbit[sub, p];
   If[Length[rpts] >= 3 &&
      MatrixRank[(# - First[rpts]) & /@ rpts, Tolerance -> w4Tol] === 2,
    Do[faceSet[Sort[vAt /@ (g . # & /@ rpts)]] = True, {g, grp}]],
   {i, 3}, {j, i + 1, 4}];
  faces = Keys[faceSet];

  (* --- the two cells meeting at each ridge ---
     A ridge lies in exactly two facets and both contain all of its
     vertices, so intersecting the per-vertex cell lists suffices. *)
  vertCells = Lookup[
    GroupBy[Flatten@MapIndexed[
       Function[{cv, k}, {# -> First[k]} & /@ cv], cellsV],
     First -> Last],
    Range[nv], {}];
  faceCells = Intersection @@ vertCells[[#]] & /@ faces;
  badRidges = Count[faceCells, x_ /; Length[x] =!= 2];

  (* --- put each face in cyclic order --- *)
  cyc[idx_] := Module[{pts, o, rel, u1, u2, ang},
    pts = verts[[idx]];
    o   = Mean[pts];
    rel = (# - o) & /@ pts;
    u1  = Normalize[First[rel]];
    u2  = Normalize@First@Select[(# - (# . u1) u1) & /@ rel,
                                 Norm[#] > w4Tol &];
    ang = ArcTan[# . u1, # . u2] & /@ rel;
    idx[[Ordering[ang]]]];
  faces = cyc /@ faces;

  (* --- edges from the cyclic faces --- *)
  edgeMap = GroupBy[
    Flatten[MapIndexed[
      Function[{f, k}, {Sort[#], First[k]} & /@ Partition[f, 2, 1, 1]],
      faces], 1],
    First -> Last];
  edges = Keys[edgeMap];

  (* --- incidences, read off the ridge construction --- *)
  cellsF = Lookup[
    GroupBy[Flatten@MapIndexed[
       Function[{ab, k}, {# -> First[k]} & /@ ab], faceCells],
     First -> Last],
    Range[nc], {}];
  faceAdj = Table[
    DeleteCases[Union @@ Lookup[edgeMap, Sort /@ Partition[faces[[k]], 2, 1, 1]], k],
    {k, Length[faces]}];

  (* vertex adjacency, to match the _4DData/f*.m convention for [[3]] *)
  vertAdj = Lookup[
    GroupBy[Join[edges, Reverse /@ edges], First -> Last],
    Range[nv], {}];

  <|"data"    -> {verts, edges, vertAdj, faces, faceAdj, cellsF},
    "cellsV"  -> cellsV,
    "counts"  -> {nv, Length[edges], Length[faces], nc},
    "order"   -> nW,
    "predV"   -> predV,
    "predC"   -> predC,
    "bad"     -> badPlanes,
    "badRidges" -> badRidges,
    "degTally"  -> Sort@Tally[Length /@ vertAdj],
    "hist"    -> Sort@Tally[Length /@ cellsV]|>];

(* ---------------------------------------------------------------- *)
(* Reporting                                                         *)
(* ---------------------------------------------------------------- *)

(* ring patterns up to the reversal symmetry of the diagram *)
w4Patterns[marks_] := Module[{all},
  all = Rest@Tuples[{0, 1}, 4];
  If[marks === Reverse /@ Reverse[marks],
   DeleteDuplicatesBy[all, Sort[{#, Reverse[#]}] &],
   all]];

w4Report[marks_, rings_, note_] := Module[
  {t, r, v, e, f, c, euler, ok, flags},
  {t, r} = AbsoluteTiming[w4Build[marks, rings]];
  {v, e, f, c} = r["counts"];
  euler = v - e + f - c;
  flags = {};
  If[v =!= r["predV"], AppendTo[flags, "V!=|W|/|stab|"]];
  If[c =!= r["predC"], AppendTo[flags, "C!=sum|W|/|W_J|"]];
  If[euler =!= 0,      AppendTo[flags, "chi!=0"]];
  If[r["bad"] > 0,     AppendTo[flags, "non-supporting plane"]];
  If[r["badRidges"] > 0,
     AppendTo[flags, "ridge not in exactly 2 cells"]];
  (* vertex-transitivity: every vertex must have the same degree *)
  If[Length[r["degTally"]] =!= 1, AppendTo[flags, "degree not uniform"]];
  ok = flags === {};
  Print[
   StringPadRight[w4Symbol[marks, rings], 10],
   StringPadLeft[ToString[v], 6], StringPadLeft[ToString[e], 7],
   StringPadLeft[ToString[f], 7], StringPadLeft[ToString[c], 6],
   "  ", If[ok, "OK      ", StringPadRight[StringRiffle[flags, ","], 8]],
   StringPadRight[ToString[r["hist"]], 30],
   StringPadLeft[ToString[Round[t, 0.01]], 7], "s  ", note];
  <|"sym" -> w4Symbol[marks, rings], "counts" -> r["counts"],
    "hist" -> r["hist"], "ok" -> ok, "data" -> r["data"]|>];

w4RunFamily[marks_, name_, notes_] := Module[{pats},
  pats = w4Patterns[marks];
  Print["\n=== ", name, " family : ", Length[pats],
        " Wythoffian members,  |W| = ",
        Length@w4Group[w4Refl /@ w4Normals[marks]], " ==="];
  Print[StringPadRight["symbol", 10], StringPadLeft["V", 6],
        StringPadLeft["E", 7], StringPadLeft["F", 7],
        StringPadLeft["C", 6], "  status  ",
        StringPadRight["cells (nverts -> count)", 30],
        StringPadLeft["time", 7]];
  w4Report[marks, #, Lookup[notes, Key[#], ""]] & /@ pats];

(* write data in _4DData/f*.m format *)
w4Export[path_, data_] := (Export[path, data, "Package"]; path);

(* ---------------------------------------------------------------- *)
(* Run                                                               *)
(* ---------------------------------------------------------------- *)

w4All = Join[
  w4RunFamily[w4MarksA, "A4",
    <|{1, 0, 0, 0} -> "5-cell", {0, 1, 0, 0} -> "rectified 5-cell",
      {1, 1, 0, 0} -> "truncated 5-cell",
      {1, 1, 1, 1} -> "omnitruncated 5-cell"|>],
  w4RunFamily[w4MarksB, "B4",
    <|{1, 0, 0, 0} -> "tesseract (8-cell)",
      {0, 0, 0, 1} -> "16-cell",
      {0, 0, 1, 0} -> "rectified 16-cell = 24-cell",
      {1, 1, 1, 1} -> "omnitruncated tesseract"|>],
  w4RunFamily[w4MarksF, "F4",
    <|{1, 0, 0, 0} -> "24-cell", {0, 0, 0, 1} -> "24-cell (dual)",
      {1, 1, 1, 1} -> "omnitruncated 24-cell"|>],
  If[w4IncludeH4,
   w4RunFamily[w4MarksH, "H4",
    <|{1, 0, 0, 0} -> "120-cell", {0, 0, 0, 1} -> "600-cell",
      {0, 0, 1, 0} -> "rectified 600-cell",
      {1, 1, 1, 1} -> "omnitruncated 120-cell"|>],
   {}]];

Print["\n", Count[w4All, KeyValuePattern["ok" -> True]], " / ",
      Length[w4All], " pass all self-checks"];

(* --- polytopes appearing in more than one family --- *)
Print["\n=== coincident combinatorial signatures across families ==="];
Do[If[Length[g] > 1,
   Print["  ", StringRiffle[g[[All, "sym"]], "  ==  "],
         "   V,E,F,C = ", First[g]["counts"]]],
  {g, Values@GroupBy[w4All, {#["counts"], #["hist"]} &]}];

(* --- cross-check the regular members against _4DData/ --- *)
(* w4Patterns keeps one representative per reversal-pair, so a symbol may
   be stored reversed; look up both spellings. *)
w4Find[sym_] := SelectFirst[w4All,
   #["sym"] === sym || #["sym"] === StringReverse[sym] &];

w4Compare4DData[] := Module[{dir, raw, got, want, eFile, eWyt, r},
  dir = DirectoryName[$InputFileName] <> "_4DData/";
  Print["\n=== cross-check against _4DData/ (V, F, C from parts 1, 4, 6) ==="];
  Do[
   raw   = Get[dir <> file];
   want  = Length /@ raw[[{1, 4, 6}]];
   r     = w4Find[sym];
   got   = r["counts"][[{1, 3, 4}]];
   eFile = Length[Union[Sort /@ raw[[2]]]];
   eWyt  = r["counts"][[2]];
   Print["  ", StringPadRight[file, 7], StringPadRight[sym, 9],
         " file=", want, " wythoff=", got,
         If[want === got, "  MATCH", "  DIFFER"],
         "   edges ", eFile, "/", eWyt,
         If[eFile === eWyt, "", "  (raw part2 = " <> ToString[Length[raw[[2]]]] <> ")"]],
   {p, {{"f5.m", "x3o3o3o"}, {"f8.m", "x4o3o3o"},
        {"f16.m", "o4o3o3x"}, {"f24.m", "x3o4o3o"}}},
   {file, {p[[1]]}}, {sym, {p[[2]]}}]];

w4Compare4DData[];
